### ISSUE TITLE
VS Code should be list in editors

### ISSUE THREAD

**Issue by crucifyml** [EMLVIRUS/Amazing-Windows-Apps#10]
Visual Studio Code is an editor like atom & sublime rather than Visual Studio IDE.

**Comment by EMLVIRUS** [comment]
Ah. How can I miss that. Sorry about that :-)

**Comment by EMLVIRUS** [comment]
fixed in [5eb0596](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/5eb0596ff7f71793ca546ac4839eb392ce5fd608)
