### ISSUE TITLE
Add ImageMagick

### ISSUE THREAD

**Issue by taroxd** [EMLVIRUS/Amazing-Windows-Apps#102]
开源软件。简单的图像处理用这东西非常方便

虽然这东西最主要的用处是放在网页后台，但是这个软件本身也非常好用

官网：https://www.imagemagick.org/index.php

用途包括但远远不限于：

格式转换 (支持平时见得到的所有格式)
`magick input.gif output.png`
`magick 1.png 2.png 3.png output.pdf`

把一张图的白底改成透明底
`magick input.png -transparent white output.png`

裁剪 (更多例子可参考一个比较老的网站 http://www.imagemagick.org/Usage/crop/)
`magick input.png -crop 32x32+16+16 +repage output.png`

缩放 (更多例子可参考一个比较老的网站 http://www.imagemagick.org/Usage/resize/)
`magick input.png -resize 64x64 output.png`
`magick input.png -filter box -resize 50% output.png`

合成
`magick destination.png source.png -gravity center -composite output.png`

BTW：还有一个软件叫 optipng，可以优化 png 图片的大小，不过用处不大，所以我就只是顺便提一下。

**Comment by EMLVIRUS** [comment]
食堂吃饭中 吃完出去约。。。深夜才能处理

**Comment by EMLVIRUS** [comment]
> 还有一个软件叫 optipng

我跟Riot比对过，貌似Riot效果更好

还是我测试方式不对？没测试错的话写了Riot就应该没必要加上了

~我提前回来了~

**Comment by EMLVIRUS** [comment]
添加于[8250280](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8250280e7cbd2f679ed8725c95bb3156278a6c16)

3Q😘

**Comment by taroxd** [comment]
optipng 是无损的，适合强迫症（逃

**Comment by EMLVIRUS** [comment]
Ahmmmm, gotcha~~~~~
