### ISSUE TITLE
安全DNS软件 Pcap_DNSProxy

### ISSUE THREAD

**Issue by venmos** [EMLVIRUS/Amazing-Windows-Apps#105]
Pcap_DNSProxy

源码仓库
* https://github.com/chengr28/Pcap_DNSProxy

下载地址
* https://github.com/chengr28/Pcap_DNSProxy/releases

软件说明
* https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe.zh-Hans.txt

完全开源的安全DNS实现，跨平台。安装建议，开发者为国人，dnscrypt.org推荐。

**Comment by EMLVIRUS** [comment]
收录同一个人的两个作品，好有♂爱

**Comment by EMLVIRUS** [comment]
@venmos 添加之后 它们居然也[在一♂起](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/1165b488f3d3caa17b1f1b7dbe8eb7f503f19672)哎💘

**Comment by venmos** [comment]
:joy:

**Comment by venmos** [comment]
@EMLVIRUS :joy:
