### ISSUE TITLE
uGet Download Manager

### ISSUE THREAD

**Issue by venmos** [EMLVIRUS/Amazing-Windows-Apps#107]
uGet Download Manager

强大的开源下载软件，跨平台(Linux/Windows/Mac/BSD/Android)，兼容支持Curl与Aria2c。

* 官方网站
http://ugetdm.com/

* 另一个开发者开发的Chrome插件兼容Chromium/Vivaldi
https://github.com/slgobinath/uget-chrome-wrapper

**Comment by lrinQVQ** [comment]
貌似不错233

**Comment by lrinQVQ** [comment]
就是貌似在win下使用起来略复杂2333 需要设置GTK3环境变量 然后貌似还要导入注册表0.0

**Comment by EMLVIRUS** [comment]
设置GTK3环境变量仅仅只是一些额外功能而已，导入注册表也是一些关联问题，这都是非必需的，因此完全无伤大雅

**Comment by EMLVIRUS** [comment]
added in [aa9975e](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/aa9975eb38aaf00b137a78522ef9ea1e77893fd1)
❤
