### ISSUE TITLE
add Startup Delayer

### ISSUE THREAD

**Issue by idongyou** [EMLVIRUS/Amazing-Windows-Apps#109]
[http://www.r2.com.au/page/products/show/startup-delayer/](url)

Startup Delayer gives you the power to optimize your Startup Process by delaying applications from starting up as soon as you log into your computer.

By delaying the applications during start up, your computer becomes usable a lot faster. Startup Delayer will then start launching your delayed applications when your computer is more idle.

**Comment by EMLVIRUS** [comment]
Thanks. I'll look into it later.

**Comment by EMLVIRUS** [comment]
There seems no update for a year and half but I didn't find obvious bug during the test.
Maybe I need to commit a piece of desciption for that.

**Comment by lrinQVQ** [comment]
0.0

**Comment by EMLVIRUS** [comment]
done by [dd851a8](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/dd851a8d038cfe664ace5cca1931bec8938ae7cb)
😘
