### ISSUE TITLE
「建议添加」Dukto 和 cmder  以及 handbrake

### ISSUE THREAD

**Issue by ZetaoYang** [EMLVIRUS/Amazing-Windows-Apps#11]
一、[Dukto](http://www.msec.it/blog/?page_id=11) ——跨平台文件传输工具， 支持的平台包含 PC 和 mobile ：
![image](https://cloud.githubusercontent.com/assets/10769951/24577755/5a52a55c-1706-11e7-98ab-ca1e9adc002a.png)

二、[cmder](http://cmder.net/)——Portable console emulator for Windows  
三、[handbrake](https://handbrake.fr/)——开源跨平台视频转换器

**Comment by EMLVIRUS** [comment]
handbrake已存在
https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/video.md#L7

**Comment by EMLVIRUS** [comment]
added in [a1c283c, fdadf7a and 56a748f](https://github.com/EMLVIRUS/Amazing-Windows-Apps/compare/3c71945f98...56a748ff2e)
