### ISSUE TITLE
建议在 “开发工具” 中加入 ConEmu

### ISSUE THREAD

**Issue by ysc3839** [EMLVIRUS/Amazing-Windows-Apps#116]
开发工具中已有 Cmder，其中包含了 ConEmu。但我不需要 Cmder 额外附带的工具，而且 Cmder 没有安装包，所以建议加入 ConEmu。
官网链接: https://conemu.github.io/

**Comment by EMLVIRUS** [comment]
给你label完就上车

**Comment by ysc3839** [comment]
如果你同意的话那我有时间就发PR。

**Comment by ysc3839** [comment]
如果你同意的话那我有时间就发PR。

**Comment by lrinQVQ** [comment]
发发发２３３３

**Comment by EMLVIRUS** [comment]
@ysc3839 嘛 PR这种东西 一直不闲多的啦（但是我现在没法用手机给review就是了）

**Comment by lrinQVQ** [comment]
我没问题的啦
