### ISSUE TITLE
应用应当符合开箱即用原则

### ISSUE THREAD

**Issue by giveup** [EMLVIRUS/Amazing-Windows-Apps#17]
需要额外运行库或复杂配置才能使用建议作为扣分项.

**Comment by EMLVIRUS** [comment]
列表的大多数应用都是不需要额外运行库的（或者会在安装包集成必须库）至于复杂配置

**Comment by lrz0** [comment]
需要更复杂配置一般代表给用户更多的自主权或拥有更多功能，个人觉得是良心软件的特征之一。

**Comment by EMLVIRUS** [comment]
> 需要更复杂配置一般代表给用户更多的自主权或拥有更多功能，个人觉得是良心软件的特征之一。

赞同的说💘

**Comment by giveup** [comment]
@lrz0 @EMLVIRUS 
我的意思是要经过一番配置才能运行的. Atom 就是开箱即用.但也提供很多个性化配置.

**Comment by WanderMax** [comment]
运行库 一般就是VC和.Net 吧

**Comment by giveup** [comment]
@WanderMax Java.
