### ISSUE TITLE
建议添加qttabbar

### ISSUE THREAD

**Issue by momoca** [EMLVIRUS/Amazing-Windows-Apps#18]
http://qttabbar.wikidot.com/
虽说是几年前的软件.但是不管是软件功能还是兼容性都没的说.可以定制的内容也超多.

**Comment by EMLVIRUS** [comment]
我曾经注意到这个应用，但是不清楚是否已经被弃坑
我看看兼容怎么样吧

**Comment by EMLVIRUS** [comment]
目前暂时没有发现兼容问题
为严谨考虑，我会先用删除线表示，等待后续观察再做处理

**Comment by momoca** [comment]
东西是真的好,不只是加个tab还对文件过滤,内容预览,支持正则匹配文件名变色.变背景色.总之特别丰富的功能.
我一直也期待它的更新.论坛中有好多人问.但似乎做者在忙别的.
我感觉它不更新的原因.似乎也再没有什么新的功能可以加上了.也没有bug.
`对了.还有个特别的就是鼠标移动上预览视频和文件还支持快进播放暂停.文件支持翻页.等等等吧.`

**Comment by EMLVIRUS** [comment]
[已添加](https://github.com/EMLVIRUS/Amazing-Windows-Apps/compare/1efd90f677...d4666bec34)

**Comment by EMLVIRUS** [comment]
@momoca 若应用有后续进展，请重新open此issue

**Comment by momoca** [comment]
了解 @EMLVIRUS
