### ISSUE TITLE
可不可以使用RSS输出最近的更新内容

### ISSUE THREAD

**Issue by monkey-sking** [EMLVIRUS/Amazing-Windows-Apps#21]
可不可以使用RSS输出最近的更新内容

**Comment by EMLVIRUS** [comment]
这是github内置的功能

1. 点击右上角
![image](https://cloud.githubusercontent.com/assets/16912240/25122526/d3acec42-2457-11e7-92c6-b3520b5831e1.png)

2.返回你的GitHub首页，底部可见链接
![image](https://cloud.githubusercontent.com/assets/16912240/25122558/e95b5d6c-2457-11e7-8696-c4e6d51740e4.png)

更多GitHub使用细节可以看我的另一个[book](https://github.com/EMLVIRUS/GitHub-Beginners)

**Comment by EMLVIRUS** [comment]
不过详细输出的话可以转到gitbook的RSS输出

**Comment by EMLVIRUS** [comment]
暂时close
如果其它疑问，请重新open

**Comment by monkey-sking** [comment]
非常感谢各位！
