### ISSUE TITLE
关于驱动和软媒

### ISSUE THREAD

**Issue by StrollStars** [EMLVIRUS/Amazing-Windows-Apps#23]
1.软媒系列加入了流氓名单，可否问下它有哪些动作？因为我用的是绿色版中的几个文件，所以没怎么发现。
2.流氓名单加入了几个老牌的驱动软件，但是硬件相关没看到合适的替代品，这样就产生了空白，希望能有好的补上。

**Comment by Explorare** [comment]
同关注，希望找一个干净的驱动管理软件。

**Comment by EMLVIRUS** [comment]
加入的理由是十分简单的：在隐私权协议中未声明的数据收集行为
本列表中的所有软件都以官方版本为准，并未考虑第三方版本，README当中也有说明

此外关于驱动管理问题，可以暂时使用系统设备管理器的自动驱动安装功能，或者生产商官网（如联想官网驱动下载页面、AMD官网等），之后我会继续寻找

**Comment by EMLVIRUS** [comment]
之前忘了提到 可以尝试Iobit公司的Driver Boost，但是由于比较有争议，故而未列入

**Comment by StrollStars** [comment]
@EMLVIRUS 感谢告知。
①关于软媒系列，你指的可是他家的魔方？你说的“数据收集”是从其上传文件还是扫描文件看出来的？就我这里看，其没有任何联网的行为。我所用的魔方是官方绿色版，在其[下载页面](http://mofang.ruanmei.com/)“立即下载”按钮右边就是，如果可能烦请帮忙测试下，然后我们再交流。
PS：本人只是一般软媒用户，和软媒无任何利益关系，也不想洗白。如果发现它确实有我所未注意到的行为，立马替换。
②关于驱动管理，看看[IT天空](https://www.itsk.com/)的[万能驱动](https://www.itsk.com/thread-375417-1-1.html)和[总裁驱动](http://www.drvceo.com/)怎么样。
③关于意外情况，我觉得非产品本身问题不应该作为不入选的理由，更何况这不是开发商的问题。争议如果不是产品本身的，也不应作为不入选的理由。在产品后加备注更好些，比如域名的污染问题。

另外请教下，Dukto是不是停更了？我这里发现，大文件从Window传输到Android结束后，Android上的客户端会直接退出，当然文件本身传输完整。
PS：建议增加下载工具一类。

**Comment by EMLVIRUS** [comment]
1/2  现在我在虚拟机当中观察，后续我会继续跟进
3  我正在修改中，会给出说明
4  dukto目前虽然一定时间未更新，但是我自己并未发现bug，也许是设置问题？

**Comment by EMLVIRUS** [comment]
3. 已经添加于[c874959](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/c8749591e71f1edc102b921b801f551fc2438ee7)

**Comment by EMLVIRUS** [comment]
黑名单描述修改延时，优先完成 #13

**Comment by EMLVIRUS** [comment]
已确认软媒魔方便携版存在强制的额外模块使用行为，并且通过实现方式为木马式植入，故而弱化系统安全性；
此外软媒系列包含但不限于魔方，包含所有软媒系列软件

黑名单中描述已于[1662686](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/16626867bcd27124d82ac542937f533a79469004)中修改，暂时close此issue

此外，如果有关于软媒系列软件中任何软件应该被排除的信息，请重新open
