### ISSUE TITLE
推荐

### ISSUE THREAD

**Issue by venmos** [EMLVIRUS/Amazing-Windows-Apps#24]
环境变量编辑 Rapid Environment Editor https://www.rapidee.com/en/about
桌面翻译软件 QTranslate https://quest-app.appspot.com/
SSH客户端 Bitvise SSH https://www.bitvise.com/index
进程管理 Process Hacker http://processhacker.sourceforge.net/
MySQL MSQL 数据库管理 https://www.heidisql.com/
Debug x64dbg http://x64dbg.com/#start
BT边下边播(用过的速度最快的) WebTorrent https://webtorrent.io/
文件文件夹对比 Meld http://meldmerge.org/

都是免费软件

**Comment by EMLVIRUS** [comment]
Web Torrent已存在于[Internet](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/internet.md)分类下

**Comment by EMLVIRUS** [comment]
已添加 感谢贡献 😘
