### ISSUE TITLE
阿呆喵为什么进入黑名单了？

### ISSUE THREAD

**Issue by GianisLee** [EMLVIRUS/Amazing-Windows-Apps#25]
一直在用这个广告过滤的软件，这个软件有什么问题吗？还是广告过滤软件有原罪？希望给个比较清楚的解释，谢谢！

**Comment by EMLVIRUS** [comment]
同 #23 ，一样都是隐私权协议中未明确说明的数据遥感收集行为
目前在官网与软件本身均未见更新说明
您现在有关于这方面的信息的话可以[邮件](mailto:EMLVIRUS@outlook.com)我说明

**Comment by EMLVIRUS** [comment]
此外，在黑名单中已经更新说明原因，暂时close此issue

如果其它信息，请重新open
