### ISSUE TITLE
软件请求添加：护眼宝

### ISSUE THREAD

**Issue by GianisLee** [EMLVIRUS/Amazing-Windows-Apps#26]
类似于f.lux，是国产软件，支持windows，macos，Android。官网：http://www.huyanapp.com/

**Comment by EMLVIRUS** [comment]
此应用最后更新于去年10月份，虽然已经较长时间未更新，但是刚刚测试未发现明显的bug
此外 对于这个应用的信誉存在争议
因此我需要更长时间的观察

**Comment by EMLVIRUS** [comment]
此外 Andriod上目前可以尝试一下 Twilight 薄暮微光 或者 Night Shift 夜班
iOS跟iMac的话最近的系统更新应该有内置类似功能

**Comment by EMLVIRUS** [comment]
根据目前的观察结果，尚未发现信誉问题
至于是否有护眼效果，已超出本列表讨论范畴，不予理会
此外由于长时间未更新，故而暂时不放入前置的国产列表名录中并等待后续观察结果

**Comment by EMLVIRUS** [comment]
添加于[a5cf033](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/a5cf0336da80efa27dfb0695e3d0c580950495a4)

暂时close，若有后续进展或者您有更多信息，重新open
