### ISSUE TITLE
推荐应用super-search

### ISSUE THREAD

**Issue by XUANXUQAQ** [EMLVIRUS/Amazing-Windows-Apps#262]
应用名称：super-search
功能：搜索文件，提高工作效率
网站：https://github.com/XUANXUQAQ/super-search
特性：开源、免费、便携
系统支持：Windows

**Comment by gloomy-ghost** [comment]
感谢自荐提交。很巧我有在用同类的开源工具，只是作者一直没正式发布，所以没加到目录里。 目前看起来 fsearch 的实现更干净一些，如果您认为 super-search 有什么特殊优势的话欢迎补充。

**Comment by XUANXUQAQ** [comment]
我会一直改进它,保证在未来至少5年内,该软件都会不断更新。

我做它的初衷 主要是我有一些桌面美化应用,例如wallpaper engine,以及translucentTB。
但我在网上找了很久也没有找到一款真正透明而且拥有搜索管理功能的软件来配合桌面美化软件。
所以我做了它。
目前已经开始添加动画效果,后续功能会越来越强大而且美观。

**Comment by XUANXUQAQ** [comment]
该程序还有一个隐藏功能，在该目录下添加Files文件夹，该程序会将其作为优先搜索文件夹。后续会添加更多的功能。

目前计划：添加自定义快捷键，过渡动画。

**Comment by Riajyuu** [comment]
![image](https://user-images.githubusercontent.com/16912240/72199202-c1a34a00-3430-11ea-87bc-b9658c04d1e1.png)


您似乎对一般Windows用户的情况缺乏了解？

**Comment by XUANXUQAQ** [comment]
这是我的一个疏忽,到学校才想起来,下一个版本会加上的。

**Comment by XUANXUQAQ** [comment]
已经修复全局搜索问题，以及文件更新问题，集成jre运行环境。
