### ISSUE TITLE
EagleGet被火绒安全报安全威胁

### ISSUE THREAD

**Issue by kongxi0071** [EMLVIRUS/Amazing-Windows-Apps#27]
如题，两个软件都是项目中入库软件，我不懂技术完全是出于新人，在火绒报告安全威胁的情况下还是安装了EAGLEGET。请帮忙合适问题，另外EAGLEGET在安装结束后有提示安装其他应用的步骤（默认为允许），若不小心很容易安装其他软件，这个应该和国产软件一样属于流氓行为吧。
辛苦项目组的朋友们的无私贡献，为你们点个大大的赞。

**Comment by kongxi0071** [comment]
截图 [https://drive.google.com/open?id=0B-igoTpY7I2fRDd1QWYyZUJNdk0](url)

**Comment by kongxi0071** [comment]
截图：https://drive.google.com/open?id=0B-igoTpY7I2fRDd1QWYyZUJNdk0

**Comment by EMLVIRUS** [comment]
这个问题 我前几天就注意到了

首先这其实属于法律漏洞，因为这并不属于捆绑安装包的行为，具体行为是联网下载目标安装包再安装（不过结果一样就是了）

而且目标推广应用也有完善的隐私权协议、使用条款等，没有明显恶意行为

现在来说，如果介意，可以尝试一下FDM

后续处理的话，我会添加必要的说明

**Comment by kongxi0071** [comment]
另外，本人已疯，谷歌浏览器首页被hao123劫持，我不知道是安装哪个程序后出现的问题，我前后安装了好几个目录中的程序。因为是连续安装的，所以不能确定具体是哪一个程序。实在可恶。正在找方法清除。

**Comment by EMLVIRUS** [comment]
> 我前后安装了好几个目录中的程序

请问 您都安装了哪些呢

**Comment by kongxi0071** [comment]
尽量按时间顺序回忆：
1.Snipaste
2.Huorong Security
3.Bandizip
4.EagleGet(已卸载，除了被报病毒威胁，另有诱导安装，重启电脑后系统提示数字证书问题)
5.honeyview（已卸载）
6.QTranslate（已删除，高度怀疑此程序）
7.aria2（不知如何用，下载后运行了一次EXE文件，后删除）
大概就这些，实在想不起来的，我喜欢乱折腾。基本上装上试用下觉得好留下，不好的就直接卸了。

**Comment by EMLVIRUS** [comment]
除了QTranslate之外的应用我已经测试过很长时间，并未发现问题
QTranslate为 #24  提出建议添加 我在虚拟机测试的时候未发现问题

现在我再看看

**Comment by kongxi0071** [comment]
我用了adwcleaner清理了一遍还是没用。试了好多种方法了。全都没有用。
知乎上有个说法说是一段VBScript调用系统服务，这个太复杂了，真不知道怎么搞定啊！https://www.zhihu.com/question/21781177  
求您帮忙一下吧，我崩溃了！

**Comment by venmos** [comment]
Chrome清理工具 https://www.google.com/chrome/cleanup-tool/

**Comment by EMLVIRUS** [comment]
此外 #24  提出人 @venmos 跟我使用QTranslate均暂未未发现问题

**Comment by kongxi0071** [comment]
但是我真的没有安装过的别的东西，今天一下午都在折腾这里项目里的软件。
google的修复工具我用了，感谢 @venmos   @EMLVIRUS  可能是我自己使用的问题吧，谢谢二位

**Comment by kongxi0071** [comment]
百度网盘是我唯一装的软件，但是已经装了很久了！

**Comment by kongxi0071** [comment]
我找到问题原因了！是火绒安全这个不要脸的东西。

**Comment by EMLVIRUS** [comment]
火绒的话 是有设置可以取消的。。。。。。。。。。。。。。。。

**Comment by kongxi0071** [comment]
我用了它的防护中心的浏览器保护，刚才取消那个保护，就恢复了正常。

**Comment by EMLVIRUS** [comment]
> 防护中心的浏览器保护，刚才取消那个保护

这个有具体设置可以关闭的，您可以尝试仔细查看一下

总之，对您造成的不便表示歉意

**Comment by EMLVIRUS** [comment]
此外，对于诱导安装的说明已经commit，暂时close此issue
如有其它问题，请重新open此issue

**Comment by kongxi0071** [comment]
这个设置埋在了下一层菜单中，不仔细找根本不会注意，它是默认锁定hao123为启动页，这不算流氓行为么？

**Comment by EMLVIRUS** [comment]
严格来说，这属于返利链接行为，如果不强制用户修改，便不会有任何问题
但是其实，这也算做一种法律漏洞的利用。该怎么处理也没有严格规范。

不过请放心，这类应用在本列表中其它应用中完全不存在（包含诱导安装的话也就四五个吧）

**Comment by shrderek** [comment]
火绒的安全规则策略是有一定问题的，非常不适合小白或者大白级用户使用的，调教不好会造成系统兼容性问题。在火绒的官方论坛评价其实一直不太好，因为有些安全规则实在闹心，我个人不推荐使用。

**Comment by EMLVIRUS** [comment]
目前来说。使用得当还是相当给力的

不过EagleGet也确实有点打擦边球。。。
