### ISSUE TITLE
推荐卸载工具GeekUninstaller

### ISSUE THREAD

**Issue by ADeadCat** [EMLVIRUS/Amazing-Windows-Apps#29]
可以自动删除残留文件，官网：https://www.geekuninstaller.com/

**Comment by EMLVIRUS** [comment]
这个应用早有耳闻，就是健忘症晚期。。。😅

**Comment by EMLVIRUS** [comment]
添加于[8a854e2](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8a854e294f6b0ffe1aa821e455044d1e87d49000)

再次感谢您的提醒

**Comment by ADeadCat** [comment]
哈哈，可以理解。
另外，有没有考虑收录一些优秀的UWP应用？（好吧，我指的就是网易云音乐😁）

2017-04-20 11:15 GMT+08:00 EMLVIRUS <notifications@github.com>:

**Comment by EMLVIRUS** [comment]
UWP的话 我并未觉得有什么可收录的

至于网易云音乐，我觉得还不如Groove

我再看看吧
