### ISSUE TITLE
推荐一个简约的音乐播放器mcool

### ISSUE THREAD

**Issue by ADeadCat** [EMLVIRUS/Amazing-Windows-Apps#30]
颜值和极简是它的两大特点。官网（应该是官网吧:sweat_smile:）：http://mcool.appinn.me/

**Comment by EMLVIRUS** [comment]
添加于[9409113](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/94091135b974ec78512688ea6ef17d75a398114d)

感谢
