### ISSUE TITLE
UWP应用 EarTrumpet

### ISSUE THREAD

**Issue by EMLVIRUS** [EMLVIRUS/Amazing-Windows-Apps#31]
由derek sheng通过telegram提出

https://www.microsoft.com/zh-cn/store/p/eartrumpet/9nblggh516xp
开源地址：https://github.com/File-New-Project/EarTrumpet

@ADeadCat 这是一个计划添加的UWP应用
 
不过有点打脸的是README中说明要求兼容7/8.1/10 (￣ε(#￣)

所以我想在怎么描述的好

**Comment by EMLVIRUS** [comment]
顺带一提 我也在想修改登录背景那个应用该怎么处理。。。

**Comment by EMLVIRUS** [comment]
该issue完成于[657cade](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/657cade2b2e3afc6ce5bcea6c698ee2bc0a36f59)

**Comment by ADeadCat** [comment]
1、这个项目的最大意义是收集、整理、推荐优秀的windows应用，具体支持哪个版本的系统不应该成为重点，只要在说明里描述清楚就可以了。
2、UWP应用现在总量还比较少，优秀的就更少了，可以考虑单独建立一个分类。

2017-04-20 13:14 GMT+08:00 EMLVIRUS <notifications@github.com>:

**Comment by EMLVIRUS** [comment]
1. 说的好有道理
2. 有些应用作者本人会明确表示有单独的UWP版本，到时候怎么处理又是一个难题，或者我到时候会单独找个logo。目前的话维持现状（用header 6注释标注）

**Comment by shrderek** [comment]
这个应用不只是调整uwp类应用的音量，其他软件也可以调整的，希望修改描述

**Comment by EMLVIRUS** [comment]
@shrderek 修改已完成，另已添加GitHub描述
