### ISSUE TITLE
New recommendation

### ISSUE THREAD

**Issue by venmos** [EMLVIRUS/Amazing-Windows-Apps#32]
* Process Lasso https://bitsum.com/
自动实时调节优化系统进程,老机器很有效,有效预防卡机.有中文.
* PingView http://www.nirsoft.net/utils/multiple_ping_tool.html
批量Ping多个主机名或IP地址,实时显示结果,并可导出HTML,TEXT,XML.
* cFosSpeed https://www.cfos.de/zh-cn/cfosspeed/cfosspeed.htm
网络速度优化加速,效果明显.有中文.

**Comment by EMLVIRUS** [comment]
刚刚小睡一觉 刚刚醒😪

**Comment by EMLVIRUS** [comment]
完成于[52c6991](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/52c6991ff8e4395421835c7fe2dcb9e0b8588e81)

阿里嘎多

**Comment by venmos** [comment]
:smile:

**Comment by EMLVIRUS** [comment]
@venmos 之前因为Process Lasso跟cFosSpeed需要付费，暂时没有考虑；
不过既然有用户提出，那么或许应该重新考虑一下

**Comment by EMLVIRUS** [comment]
done again
