### ISSUE TITLE
推荐软件——文件/文件夹对比工具 WinMerge

### ISSUE THREAD

**Issue by aixlx** [EMLVIRUS/Amazing-Windows-Apps#33]
文本处理分类中，推荐了 Meld，经自己的体验么，WinMerge 更好用一些。

官网：http://winmerge.org/
简介：WinMerge is an Open Source differencing and merging tool for Windows. WinMerge can compare both folders and files, presenting differences in a visual text format that is easy to understand and handle.

**Comment by EMLVIRUS** [comment]
请问 相对于Meld的区别点在哪里呢？

**Comment by aixlx** [comment]
说几点差别吧：
1. WinMerge 支持从右键菜单调用，这样在想对比的文件夹/文件右键，再添加另一个待对比对象即可，不用从Meld的主界面一个个点过去（此外，Meld用了自己实现的一套文件选取工具，很不好用，而WinMerge调用了系统的文件选取控件，借助Listary的快速切换功能，定位到文件夹非常方便）
2.  WinMerge支持中文
3.  WinMerge有工程的概念，适合对某类结果多次进行对比，还有诸多功能，而Meld的功能感觉好简陋。

除了只支持 Windows平台，以及最近的realease date为2013-02-03——新版本还在研发外，没什么缺点。不过 WinMerge本身是很成熟的软件了。

**Comment by EMLVIRUS** [comment]
> 最近的 realease date 为 2013-02-03——新版本还在研发外

的确，尽管长期未更，但是刚刚经过虚拟机的简单测试并未发现bug

我会先进一步观察一会，如果未发现bug，那么在commit时会使用header 6注释说明

**Comment by EMLVIRUS** [comment]
commit完成，感谢您的建议
