### ISSUE TITLE
推荐软件-PDF软件Master PDF Editor

### ISSUE THREAD

**Issue by juqkai** [EMLVIRUS/Amazing-Windows-Apps#34]
Master PDF Editor跨平台, 而且在多个平台上表现都比较优秀, 支持中文.
使用起来非常顺畅, 相对其它PDF软件来说比较小巧, 该有的都有, 不该有的基本没有.

官网: https://code-industry.net/masterpdfeditor/
简介: It is simple and comfortable application for work with PDF documents equipped with powerful multi-purpose functionality. With Master PDF Editor you can easily view, create and modify PDF documents. The application enables you to merge several files into one and split source document into multiple ones, and also to comment, sign and encrypt PDF files.

**Comment by EMLVIRUS** [comment]
目前我正在尝试中英分离操作，见 #13 

所以对于这一应用（包括完成分离前所有推荐请求）的添加会推迟

感谢建议

**Comment by EMLVIRUS** [comment]
这个官网的证书位于已不被明确信任的根证书下？

请问，您有发现这个情况吗？

**Comment by juqkai** [comment]
咦, 刚看了一下, 没有这个问题呢

**Comment by EMLVIRUS** [comment]
请问，您访问官网，显示的证书签发机构是哪一个呢？
如果是以下的其中之一，那么确实是不被信任的：

1. Startcom  高通
2. Wosign   沃通
3. CNNIC

**Comment by EMLVIRUS** [comment]
我刚刚使用虚拟机访问官网，确认https://code-industry.net/masterpdfeditor/ 证书签发机构为Startcom

Startcom根证书已不被信任，这意味着使用任何来自Startcom证书的HTTPS会话均暴露于风险中

暂时close，如果该应用后续更新被信任的HTTPS根证书或有其他信息，请重新open
