### ISSUE TITLE
软件推荐-效率工具Clover 

### ISSUE THREAD

**Issue by juqkai** [EMLVIRUS/Amazing-Windows-Apps#36]
多语言支持, 有广告, 可以关闭

官网: http://cn.ejie.me/
简介: 为您的 Windows Explorer 插上翅膀！
Clover 是 Windows Explorer 资源管理器的一个扩展，为其增加类似谷歌 Chrome 浏览器的多标签页功能。

**Comment by EMLVIRUS** [comment]
有人曾经在telegram跟我提过，不过由于广告位于前台，影响使用故而未列入

既然再提出来，我再具体看看吧

**Comment by EMLVIRUS** [comment]
于[7221167](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/7221167568433b9cca09089e6820d32ae39f1d83)提交并重新归为系统增强分类

此外，确认存在侵入式广告嫌疑，故此：

1. 使用删除线表示且未提供官网信息
2. 暂未添加国产名录与总应用计数中 等待后续观察

若有后续变动信息，请重新open
