### ISSUE TITLE
软件推荐-系统工具RDCMan

### ISSUE THREAD

**Issue by juqkai** [EMLVIRUS/Amazing-Windows-Apps#39]
微软出品
多远程桌面管理软件(RDCMan.exe，RDC - Remote Desktop Connection Manager), 适合大量远程桌面的管理. 很方便进行管理. 
可能现在用得不多...
官网: https://www.microsoft.com/en-us/download/details.aspx?id=44989

**Comment by EMLVIRUS** [comment]
该应用长期未更新且未能兼容Windows7/10，但是在设计上此类应用实现兼容的难度较小，故此暂不列入

若有后续变动信息，请重新open
