### ISSUE TITLE
软件推荐-视频播放器SMPlayer

### ISSUE THREAD

**Issue by hizjz** [EMLVIRUS/Amazing-Windows-Apps#40]
SMPlayer 是个适用于 Windows 和 Linux 的免费媒体播放器， 内置解码器，可以播放几乎所有格式的视频和音频文件。 无需再安装任何外部解码器。 只要安装了 SMPlayer， 你就能够播放所有的格式，不用再费事查找安装解码包

SMPlayer 最有趣的一个功能是：它会记住您播放过的所有文件的设置。 因此，当您在看一部电影时， 但有事得走... 不用担心，当您再次打开那部电影时， 它将恢复到您离开时的播放位置，并使用相同的设置： 音轨、字幕、音量...

SMPlayer 是个用于屡获殊荣的 MPlayer 的图形化界面 (GUI)， 它能够播放几乎所有已知的视频和音频格式。 但除了提供MPLayer的大多数常用命令外 SMPlayer也有一些好玩的特性，例如 支持播放Youtube视频和下载字幕。

有32位、64位版本，一直在持续更新，基本上一个月更新一次。
开源无广告，界面简洁，功能实用但不复杂，常见视频都能播放，内置多语言，基本上一个良心软件该有的都有。
主页https://sourceforge.net/projects/smplayer/

**Comment by EMLVIRUS** [comment]
现在优先完成 #13 任何软件添加暂缓

**Comment by EMLVIRUS** [comment]
添加于[8b02960](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8b029608c97056921f98eab3bc4c1a932c8d18ad)

感谢建议
