### ISSUE TITLE
软件推荐--文本编辑器--LeaNote

### ISSUE THREAD

**Issue by iplaywind** [EMLVIRUS/Amazing-Windows-Apps#41]
LeaNote是一款支持 MarkDown 的云笔记，开源程序，支持年度付费使用官方云同步，也可以使用代码自己搭建云服务器。LeaNote 与Inkdrop极其相似（界面也极其相似），但是价格远低于Inkdrop。
官网地址：www.leanote.com

**Comment by EMLVIRUS** [comment]
感谢您的建议

不过 由于刚刚完成 #13 ，现在身心疲惫，无力检查新应用，故此本应用添加会等到明天😅

**Comment by EMLVIRUS** [comment]
作为一款具备云端功能的笔记是应当引入隐私权协议的，但是我未能在官网与应用本身发现

@iplaywind 请问您有发现其隐私权协议的位置吗？

**Comment by iplaywind** [comment]
你好，抱歉，关于隐私权协议，我确实没有太关注这一方面，给你们造成了困惑。
我自己也找了官网和软件，也没有看到相应的关于隐私权的内容，所以如果使用官方的云服务，我觉得可能会不太靠谱吧？
但是这是一个开源的程序，可以用来自购服务器和搭建云笔记。

**Comment by EMLVIRUS** [comment]
是的，自建云服务确实不需要引入隐私权协议

但是本例中该应用提供商明显提供了自身的商用云服务，这就必须引入隐私权协议

虽然不排除有不会介意的用户，但是这并不适合在此处列入

此issue暂时close，如果该应用提供商提出了隐私权协议，请重新open

**Comment by EMLVIRUS** [comment]
@iplaywind 现在我通过QQ群组已与官方人员取得联系，目前他们正在确认这一问题，若有后续变动，此应用会被重启审核

**Comment by lealife** [comment]
Leanote服务条款 https://pro.leanote.com/p/591adc52893c0fe74a2c67ae

**Comment by EMLVIRUS** [comment]
鉴于已提出隐私权协议，该应用重启审核

**Comment by EMLVIRUS** [comment]
完成于[164c5b7](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/164c5b7535d7fe284291118a5faae8a25fb0276f)
