### ISSUE TITLE
软件推荐--文本编辑器--EmEditor

### ISSUE THREAD

**Issue by WanderMax** [EMLVIRUS/Amazing-Windows-Apps#43]
EmEditor 是快速，轻巧，可扩展，使用方便的 Windows 文本编辑器。同时支持32位和64位版本！

ZDnet.com 的 Ed Burnette 称 EmEditor 为 “全球最快的文本编辑器”。

日本人气网站窓の杜 (Mado-no-mori) 评价，“无需 Excel。最强 CSV 编辑器”。

EmEditor 文本编辑器支持宏，Unicode，还能处理大数据以及 CSV 文件。Emurasoft 公司致力于随时倾听并满足客户的需求。我们提供及时的客户服务, 并希望通过不断地技术更新来更好地服务于客户。我们的客户包括：大中小企业，教育机构，欧盟组织，银行，以及各国的政府部门。

官网https://www.emeditor.com/

**Comment by EMLVIRUS** [comment]
添加于 [c0d8b0a](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/c0d8b0a249bda4bd03b5d894851692202e45dc0d)

感谢建议
