### ISSUE TITLE
软件推荐--对比工具--Beyond Compare

### ISSUE THREAD

**Issue by WanderMax** [EMLVIRUS/Amazing-Windows-Apps#44]
Beyond Compare是一款功能强大、不可多得的文件对比工具，这款软件可以快速找出两个文件的区别，并把不同的地方用颜色区分开来，方便后续的查看；Beyond Compare还内置了专业的文件浏览器，能够协调源代码、文件夹、图像等各种文件的差异，从而帮助用户更好的进行同步和排错工作。

个人感觉对比工具无人出其右!

官网 http://www.scootersoftware.com

**Comment by EMLVIRUS** [comment]
请问，这应该是有试用期但是需要付费的软件把

**Comment by WanderMax** [comment]
是的
记得是30天还是多少

**Comment by EMLVIRUS** [comment]
添加于[c1e068a](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/c1e068abed0f1d7cd550aea10f230f48c4bbdb66)
