### ISSUE TITLE
软件推荐--批量文件更名工具--菲菲更名宝贝

### ISSUE THREAD

**Issue by WanderMax** [EMLVIRUS/Amazing-Windows-Apps#45]
国产个人作者应用。
免费无广告，v4正在内部开发中~~~~

http://www.ffhome.com/category/works/ffrenamepro

**Comment by EMLVIRUS** [comment]
不忍吐槽的名字。。。。。。。。

**Comment by WanderMax** [comment]
@EMLVIRUS 作者纪念他女儿嘛，个人作者，哈哈哈。
程序员的任性嘛

**Comment by EMLVIRUS** [comment]
抛开名字的问题不谈，软件最后更新日期我没找错的话是15年12月

有些时间了

我会先测试一下，没有明显bug的话会像QTabbar一样给出注释

**Comment by WanderMax** [comment]
@EMLVIRUS 最近发出的v4还在内测中，乃可以去weibo上@他

**Comment by EMLVIRUS** [comment]
> PS，晚上回去看看目前 PC 里面使用的那些，感觉都可以上推荐啊，那可是我用了 6 年，慢慢筛选的~~

请发pull request。。。。。。太多的话处理时间会大大延长。。。。

**Comment by EMLVIRUS** [comment]
[添加已完成](https://github.com/EMLVIRUS/Amazing-Windows-Apps/compare/c1e068abed...f5149a6681)
