### ISSUE TITLE
软件推荐--数据恢复--DiskGenius

### ISSUE THREAD

**Issue by yfdyh000** [EMLVIRUS/Amazing-Windows-Apps#47]
功能强大的磁盘管理、分区和文件恢复工具。

免费功能无限制使用，高级功能需付费购买。

下载页面: http://www.diskgenius.cn/download.php
功能对比: http://www.diskgenius.cn/pro/details.php

**Comment by EMLVIRUS** [comment]
[FF中文社区](https://www.firefox.net.cn/)的大佬午安😘

**Comment by EMLVIRUS** [comment]
@yfdyh000 请问这个软件是国产的吗？不是的话能否给出国际官网

**Comment by shrderek** [comment]
国际官网 http://www.diskgenius.net/download.html http://www.partitionguru.com/
国际版已改名为PartitionGuru

**Comment by EMLVIRUS** [comment]
添加于 [d33e129](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/d33e129df5f8c7355f48132ce97747c5c213e04f)

感谢二位
