### ISSUE TITLE
软件推荐--文本编辑器--EverEdit

### ISSUE THREAD

**Issue by WanderMax** [EMLVIRUS/Amazing-Windows-Apps#49]
EverEdit，专为国人设计的文本编辑器
身躯小巧，性能卓越，自定义功能完善，丰富的主题和脚本，完美的编码、大字符集字符显示，无论您是哪个级别的码农，EverEdit都会给您带来不一样的体验！

国产程序员编辑器
官网 http://www.everedit.cn/

**Comment by EMLVIRUS** [comment]
（备忘）支持中英日

需要寻找日本国旗logo

**Comment by EMLVIRUS** [comment]
添加于 [ebd56c7](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/ebd56c7998596e96470bb7a8a46652d5cedc8d20)
