### ISSUE TITLE
软件推荐 -- 隐私安全  Cryptomator

### ISSUE THREAD

**Issue by dzlzh** [EMLVIRUS/Amazing-Windows-Apps#50]
[Cryptomator](https://cryptomator.org)  云同步网盘加密工具 
- 开源免费 [GitHub](https://github.com/cryptomator)
- 跨平台支持 Windows，Mac， Linux， iOS，Android

**Comment by EMLVIRUS** [comment]
吓得我以为我的梯子服务器波动

终于确认您的头像就是白的😂

**Comment by dzlzh** [comment]
哈哈:grin:
不知道用什么头像好找了张透明图片扔上去了

**Comment by EMLVIRUS** [comment]
添加于[68673af](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/68673af496c4f84066123cdca8c03267feea7810)

感谢建议
