### ISSUE TITLE
软件推荐 视频工具 Shotcut

### ISSUE THREAD

**Issue by kmdgeek** [EMLVIRUS/Amazing-Windows-Apps#52]
少见的功能强大而且还开源的视频编辑工具。
Shotcut is a free, open source, cross-platform video editor for Windows, Mac and Linux. Major features include support for a wide range of formats; no import required meaning native timeline editing; Blackmagic Design support for input and preview monitoring; and resolution support to 4k.

官网：https://www.shotcut.org/

**Comment by EMLVIRUS** [comment]
目前GitBook服务器抽风中，我暂时无法更新

坐等客服处理。。。。

**Comment by EMLVIRUS** [comment]
自行恢复╮(╯▽╰)╭开工

**Comment by EMLVIRUS** [comment]
添加于[734b711](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/734b7111c7c55121308a67507b7ebb6912cb81af)

感谢建议
