### ISSUE TITLE
move speccy to harwares

### ISSUE THREAD

**Issue by HGladiator** [EMLVIRUS/Amazing-Windows-Apps#54]
[speccy](https://www.piriform.com/speccy)
Fast, lightweight, advanced system information tool for your PC.

**Comment by EMLVIRUS** [comment]
duplicated apps, see [practicals](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/practicals.md) category.

**Comment by HGladiator** [comment]
change  it's position to hardwares

**Comment by EMLVIRUS** [comment]
That seems make sense

**Comment by EMLVIRUS** [comment]
done by [cb346b9](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/cb346b9ee4e23feba05e94507c2a92382f8d939b)

Thanks
