### ISSUE TITLE
软件推荐：视频播放器 MPC-BE

### ISSUE THREAD

**Issue by darkskygit** [EMLVIRUS/Amazing-Windows-Apps#55]
Media Player Classic - BE 是一个Windows上免费开源的音视频播放器。
Media Player Classic - BE 基于"Media Player Classic"(MPC，Gabest)及"Media Player Classic Home Cinema"（MPC-HC，Casimir666），包含一些功能增强及bug修复。

Media Player Classic - BE is a free and open source audio and video player for Windows.
Media Player Classic - BE is based on the original "Media Player Classic" project (Gabest) and "Media Player Classic Home Cinema" project (Casimir666), contains additional features and bug fixes.

相比MPC-HC增强了UI设计及，内部解码器替换为LAVFilter，因此对硬件解码的支持相比MPC-HC会更加好，MPC-BE无运行库及其他依赖，可单文件独立运行，官方安装文件中附加的文件或组件包括：多语言支持、增强画面用shader、授权说明及更新日志、右键菜单扩展、关联媒体文件图标，如不需要均可移除。

官网：https://mpcbe.sourceforge.io/

**Comment by EMLVIRUS** [comment]
添加于 [766a339](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/766a33951aca764afb2821d72dc5a073793607d7)

感谢建议
