### ISSUE TITLE
Ebooks app:calibre

### ISSUE THREAD

**Issue by molingyu** [EMLVIRUS/Amazing-Windows-Apps#6]
website: http://calibre-ebook.com
* i18n 
* GPL v3 (github: https://github.com/kovidgoyal/calibre)

**Comment by EMLVIRUS** [comment]
adding in progress

**Comment by EMLVIRUS** [comment]
Added in [1d64a50](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/1d64a5076a402d74d6499c94cf1bc9ae5f65e023)
