### ISSUE TITLE
hashcalc

### ISSUE THREAD

**Issue by HGladiator** [EMLVIRUS/Amazing-Windows-Apps#60]
[hashcalc](http://www.slavasoft.com/hashcalc/index.htm)
	
A fast and easy-to-use calculator that allows to compute message digests, checksums and HMACs for files, as well as for text and hex strings. It offers a choice of 13 of the most popular hash and checksum algorithms for calculations.

**Comment by EMLVIRUS** [comment]
last modified date to this app is 2007, 10 years ago???
![image](https://cloud.githubusercontent.com/assets/16912240/25300545/1e7b4e78-2744-11e7-92c9-69df488e94af.png)
Maybe I need more time to check if there is any bug

**Comment by taroxd** [comment]
I would prefer to use something like `md5sum`, `sha1sum`, `sha256sum` from GNU, or `fciv` from Microsoft.

Note that sha256sum is also available in Windows. It can be obtailed along with `mingw`, `git`, `Bash on Ubuntu on Windows` or something like these.

![image](https://cloud.githubusercontent.com/assets/6070540/25301366/c8ee8cc2-2757-11e7-8610-a2aaf3dd2e15.png)

**Comment by EMLVIRUS** [comment]
Agreed with @taroxd 

And I found it really buggy on Windows 10 RS2

If there is someone who really hates command line (I don't know why :-)), I have a better recommendation, see #62

close for now yet

**Comment by HGladiator** [comment]
thanks a lot
