### ISSUE TITLE
软件推荐--文本编辑器--AkelPad

### ISSUE THREAD

**Issue by tttsss520** [EMLVIRUS/Amazing-Windows-Apps#63]
AklePad是一个开源编辑器，具有小巧、支持插件、多语言、多窗口等特点。完全免费且无广告。

官网地址：http://akelpad.sourceforge.net/en/index.php

**Comment by EMLVIRUS** [comment]
怎么看起来像在说notepad++

**Comment by EMLVIRUS** [comment]
@tttsss520 我看了半天 没发现有什么跟notepad++的区别点，反而觉得二者严重同质化

**Comment by EMLVIRUS** [comment]
@tttsss520 我又观察了一会 无法发现与其它文本编辑器之前的突出亮点 也许是我观察能力不足？可否指点一二？

**Comment by tttsss520** [comment]
轻量化啊，多语言插件版本才1MB，无插件版本才250kb。

**Comment by EMLVIRUS** [comment]
添加于[b7ab989](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/b7ab989e5dd59fa493418d74dd4df9fe48c5014f)

感谢建议
