### ISSUE TITLE
推荐

### ISSUE THREAD

**Issue by ts8zs** [EMLVIRUS/Amazing-Windows-Apps#64]
画画 MediBang Paint Pro
防火墙HIPS comodo firewall
Fence文件夹版 Nimi Places
前端 HBuilder
弹幕动漫视频 弹弹play
游戏修改 CheatEngine
文档处理 LibreOffice
虚拟机 VitualBox
GIT管理 SourceTree

还有就是360-total-security其实现在不怎么样建议从白名单移出
倒是360-total-security-essential和360驱动管理可以加上白名单 现在还算良心

**Comment by EMLVIRUS** [comment]
首先感谢建议 不过鉴于应用数量较多，处理速度会稍慢
此外您可否给出各个应用官网以减少检查工作量？

> 360-total-security 其实现在不怎么样建议从白名单移出

关于这个问题移出的是黑名单，因为其有完善的隐私权协议，也没有国内版的恶意行为，因此我没有理由拉黑

> 360-total-security-essential 和 360 驱动管理

360-total-security-essential 包含于360国际版，是否加入国产名录我会后续观察

360驱动管理一个很明显的问题是隐私权协议缺失

**Comment by EMLVIRUS** [comment]
> 文档处理 LibreOffice

见于[productivity](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/productivity.md)分类下

**Comment by ts8zs** [comment]
画画 MediBang Paint Pro https://medibangpaint.com/
防火墙HIPS comodo firewall https://personalfirewall.comodo.com
Fence文件夹版 Nimi Places mynimi.net/Projects/Nimi-Places
前端 HBuilder http://dcloud.io/
弹幕动漫视频 弹弹play http://dandanplay.com/
游戏修改 CheatEngine http://www.cheatengine.org/
虚拟机 VitualBox https://www.virtualbox.org
GIT管理 SourceTree https://www.sourcetreeapp.com

**Comment by EMLVIRUS** [comment]
> 弹幕动漫视频 弹弹play http://dandanplay.com/

该应用引入大量隐私相关的云服务，但是仅有EULA（终端使用协议）而未引入隐私权协议，故此不考虑列入

**Comment by EMLVIRUS** [comment]
添加于[a313bde](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/a313bdeaafc93d203d486ad82fd5095d2209c062)

感谢建议
