### ISSUE TITLE
另外一些比较那啥的...我就问问 JoyToKey,dexpot,Velocity 

### ISSUE THREAD

**Issue by ts8zs** [EMLVIRUS/Amazing-Windows-Apps#65]
手柄模拟键盘 JoyToKey joytokey.net //似乎不是很常用?
虚拟桌面 dexpot dexpot.de //win10似乎用不到?
编程文档查询 Velocity https://velocity.silverlakesoftware.com //免费版有查询频率限制?

**Comment by EMLVIRUS** [comment]
> 虚拟桌面 dexpot dexpot.de //win10似乎用不到?

![image](https://cloud.githubusercontent.com/assets/16912240/25310457/2f437072-2817-11e7-9d33-8336ba1f330d.png)
长期不更新且有明显兼容问题的应用是不会列入的

**Comment by EMLVIRUS** [comment]
> 手柄模拟键盘 JoyToKey joytokey.net // 似乎不是很常用?

添加于[8ad9b26](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8ad9b26773d253d88d574d6bb4c602c84c0a2b18)

其余二者显示过多未考虑列入，感谢建议
