### ISSUE TITLE
PuTTY应列为开源应用

### ISSUE THREAD

**Issue by unnamed5719** [EMLVIRUS/Amazing-Windows-Apps#68]
在[此页面](https://emlvirus.gitbooks.io/windows-apps-that-amaze-us/content/terminal.html)中
PuTTY 应列为开源应用
在[该应用首页](http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)已列出源码下载地址与git仓库地址

如确实违反此列表规定，还请告之，多谢

**Comment by EMLVIRUS** [comment]
确实 这是列表列入时的疏忽 感谢指出

**Comment by EMLVIRUS** [comment]
修改完成于[b0f952b](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/b0f952b7a5529b90fc4dd05989963a9ce974eac3)

感谢指出
