### ISSUE TITLE
remotr

### ISSUE THREAD

**Issue by ts8zs** [EMLVIRUS/Amazing-Windows-Apps#71]
http://remotrapp.com/ 可以用来玩游戏的远程控制软件……

**Comment by EMLVIRUS** [comment]
今天比较忙 估计晚上才能处理
（欢迎

**Comment by EMLVIRUS** [comment]
添加于[3bc021c](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/3bc021c0941c52705fc74781728b1750d244f443)
