### ISSUE TITLE
foobar2000 并不是开源软件

### ISSUE THREAD

**Issue by ElTopo** [EMLVIRUS/Amazing-Windows-Apps#73]
音频文件分类下的 foobar2000 简介为: "免费开源音频播放器"，但它只是无广告的免费软件。

**Comment by EMLVIRUS** [comment]
确实 这是个错误，稍后我会修改描述。感谢指正

**Comment by EMLVIRUS** [comment]
修改于[7caf8f2](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/7caf8f24c39188ecda2cfce322e17e8e770c3e0d)
