### ISSUE TITLE
GeekUninstaller

### ISSUE THREAD

**Issue by yi-Xu-0100** [EMLVIRUS/Amazing-Windows-Apps#74]
卸载软件一直很烦，偶然间发现这个`GeekUninstaller`，官网地址：<https://www.geekuninstaller.com/>

如果不错，希望能够采纳。感谢作者的整理。

---
Uninstalling the software is a confused things for me, but one time I found this helper that is `GeekUninstaller`. Official page: <https://www.geekuninstaller.com/>

It is nice to be included in the list if it is really strong for people using. Thanks for author's collection.

**Comment by EMLVIRUS** [comment]
该应用已存在，见于[system](https://github.com/EMLVIRUS/Amazing-Windows-Apps/blob/master/system.md)分类下
