### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by fengbjhqs** [EMLVIRUS/Amazing-Windows-Apps#77]
下载工具里面的
aria2，建议添加配合webui-aria2使用，
fdm3   在这里http://portableapps.com/apps 有便携版，其中fdm3好像不能跨平台，5是跨mac，

atom和vscode的解释好好奇怪，他们就是文本编辑器哇，vscode也可以是便携版，atom和vscode默认都不是便携版，需要配置。
文编编辑器  可以有https://github.com/XhmikosR/notepad2-mod   替代系统记事本的最佳选择

cmder基于ConEmu的，

数据库管理  mysql  还有MySQL-Front可以选择

sqlite3 SQLiteStudio

**Comment by EMLVIRUS** [comment]
> aria2，建议添加配合 webui-aria2 使用

aria2的web UI会视作单独的应用列入

至于软件是否编写、开源等信息，仅考虑最新版本的官网下载来源，第三方来源不予以考虑

VScode 确实需要改进描述，官网也确实提供了便携版下载，稍后我会尝试

关于新应用建议请每个应用单独一个issue

**Comment by EMLVIRUS** [comment]
[vscode描述已修改](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/ecae5c92454744afa5887159ba7978d0aa7b0bd1)
