### ISSUE TITLE
推荐Find and Run Robot 2

### ISSUE THREAD

**Issue by lingchuanbo** [EMLVIRUS/Amazing-Windows-Apps#78]
官网https://www.donationcoder.com/Software/Mouser/findrun/
推荐理由 比Wox还是Rolan还是Launchy更加高效更加高级自定义

**Comment by EMLVIRUS** [comment]
高效看人啦 有些人就是讨厌敲快捷键就得rolan

高级自定义倒是有不少

**Comment by EMLVIRUS** [comment]
添加于[8acb2d4](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/8acb2d4aa57a86debe19ad6e833360f4a5e6c52c)

感谢建议
