### ISSUE TITLE
推荐Apowersoft screen capture pro

### ISSUE THREAD

**Issue by Mistry-lee** [EMLVIRUS/Amazing-Windows-Apps#79]
### 理由:功能强大的录屏以及截屏软件,以及跨终端!

**Comment by EMLVIRUS** [comment]
您提供的是该公司的主页，您所指的是该公司所有软件还是限于[screen recorder](https://www.apowersoft.cn/screen-recorder)

**Comment by Mistry-lee** [comment]
目前我使用了[录屏王](https://www.apowersoft.cn/screen-recorder)和[screen-capture-pro](https://www.apowersoft.cn/screen-capture-pro),这两款都很不错!

**Comment by EMLVIRUS** [comment]
请为每个issue单独写一个issue，这样能加快review过程（见于[FAQ Q3](https://github.com/EMLVIRUS/Amazing-Windows-Apps/wiki)）

**Comment by EMLVIRUS** [comment]
@Mistry-lee screen-capture-pro 免费版仅允许录屏三分钟，这是严重影响体验的，故而不会考虑，以下是一些替代方案：

1. bandicam
2. licecap
3. screentogif

**Comment by EMLVIRUS** [comment]
Apowersoft screen capture pro 每次启动时均会有注册提示，我不确定这对于大多数人体验如何（反正我挺烦）
个人认为，一般来说，以下注册提示是不会影响体验的：
    * 软件退出时（见于TeamViewer）
    * 当用户尝试使用购买功能时

**Comment by taroxd** [comment]
安利一波 OBS

**Comment by EMLVIRUS** [comment]
> 安利一波 OBS

@taroxd 已存在,,ԾㅂԾ,,

**Comment by EMLVIRUS** [comment]
暂时close
