### ISSUE TITLE
ZeroNet

### ISSUE THREAD

**Issue by ts8zs** [EMLVIRUS/Amazing-Windows-Apps#82]
https://zeronet.io/
开放，自由，去中心化的网络通讯

**Comment by EMLVIRUS** [comment]
所以 到底是来干什么的呢 有点没看懂

**Comment by ts8zs** [comment]
一个基于p2p的。。。局域网？

**Comment by EMLVIRUS** [comment]
添加于[0f912ce](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/0f912ceb10d9c275b42dd1acc2d4fc4c88e92fd6)

（感谢再次发现
