### ISSUE TITLE
okular

### ISSUE THREAD

**Issue by yi-Xu-0100** [EMLVIRUS/Amazing-Windows-Apps#84]
>Okular is a universal document viewer based developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, *BSD, etc.
>Okular is a Free Software PDF reader.

Office pages:<https://okular.kde.org/>

**Comment by EMLVIRUS** [comment]
Hey, could you provide the download link as well?
It can't find it anywhere on its site so is it provided in an external location?

**Comment by yi-Xu-0100** [comment]
抱歉，我看到他的介绍有说到可以在`windows`运行，就提交了`issue`，个人实践查找后，发现他的安装是在`KDE`下，对环境有要求，没有直接运行的可执行文件，整体安装过程也较为复杂，并不适合这个推荐。带来不便请见谅，下次我会认真求证，避免这样的问题。
