### ISSUE TITLE
PotPlayer的开源许可证问题

### ISSUE THREAD

**Issue by shensven** [EMLVIRUS/Amazing-Windows-Apps#85]
[这个页面](https://github.com/FFmpeg/web/blob/master/src/shame#L63-L65)报道了 PotPlayer 存在违反 FFmepg 许可证的行为，具体情况我不太清楚，你们也应该看看

**Comment by EMLVIRUS** [comment]
处理于[96739e4](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/96739e40712642e4dd2bc5a1d46ac0ff4f32691c)：
- 添加协议违反描述
- 移除官网链接
- 从总计数中排除
