### ISSUE TITLE
软件推荐--实用程序--傲梅分区助手

### ISSUE THREAD

**Issue by tttsss520** [EMLVIRUS/Amazing-Windows-Apps#94]
傲梅分区助手是一款国产磁盘软件，具有调整磁盘分区大小，分割分区，合并分区，克隆与迁移系统等功能。免费无广告且功能强大，可以置入到PE当中作为功能增强。
官方网站：http://www.disktool.cn/feature.html

**Comment by EMLVIRUS** [comment]
计划归于system分类

**Comment by tttsss520** [comment]
需要密切观察并且跟踪，怀疑有广告化倾向

**Comment by EMLVIRUS** [comment]
> 密切观察并且跟踪，怀疑以后会有广告化倾向
 参见火绒

**Comment by tttsss520** [comment]
@EMLVIRUS 在目前官方网站最新的分区助手专业版6.2版本当中，没有发现任何可疑操作和 不当设置。我也查看了用户协议，没有发现有重大误解、显失公平、胁迫用户的条文。目前来说，值得将它列入推荐表单。

**Comment by EMLVIRUS** [comment]
添加于 [a57bc75](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/a57bc75c6ae425d370804129f92a9a18e6e752af)

如有后续变动 请重新open
