### ISSUE TITLE
Duplicate cleaner

### ISSUE THREAD

**Issue by yi-Xu-0100** [EMLVIRUS/Amazing-Windows-Apps#99]
[Duplicate cleaner](https://www.digitalvolcano.co.uk/duplicatecleaner.html)是文件比较器，支持子目录搜索，找到重复文件，可以基于MD5码，支持多国语言。

**Comment by EMLVIRUS** [comment]
添加于[53561f6](https://github.com/EMLVIRUS/Amazing-Windows-Apps/commit/53561f69afab52ae2e99723febb80a6cfdf67e37)

感谢您的建议
